name: shorty app build

on:
  push:
    branches:
      - "main"
    paths:
      - "shorty/**"

env:
  VERSION: ${{ github.sha }}

jobs:

  build:
    name: build go app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: get go version
        run: go version
      - name: install deps
        working-directory: shorty
        run: go get ./... && go mod tidy
      - name: build app
        run: go build -o bin/shorty-app shorty/main.go
      - shell: bash
        run: |
          echo "go binary compiled"
          ./bin/shorty-app