name: shorty app build

on:
  push:
    branches:
      - "main"
    paths:
      - "shorty/**"

env:
  VERSION: ${{ github.sha }}

jobs:

  build:
    name: build go app
    runs-on: ubuntu-lates
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - run: go version
      - run: go build -o shorty shorty/main.go
      - shell: bash
        run: |
          echo "go binary compiled"
          ./shorty